# Platform
TARGET_BOARD_PLATFORM := sc8830

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
TARGET_CPU_VARIANT := cortex-a7


# TARGET_GLOBAL_CFLAGS += -Wno-error=implicit-fallthrough
# TARGET_GLOBAL_CPPFLAGS += -Wno-error=implicit-fallthrough

# Bootloader
TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := Plane_7565N_3G

TW_DEFAULT_LANGUAGE := ru
TW_DEVICE_VERSION := by mehanik6 (4pda.ru)

# Kernel
TARGET_PREBUILT_KERNEL := device/digma/plane_7565n/kernel
BOARD_KERNEL_CMDLINE := console=ttyS1,115200n8
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 2048
# BOARD_KERNEL_SEPARATED_DT := true
BOARD_MKBOOTIMG_ARGS := --dt device/digma/plane_7565n/dt.img --kernel_offset 0x00008000 --ramdisk_offset 0x01000000 --tags_offset 0x00000100

# Partitions
#BOARD_BOOTIMAGE_PARTITION_SIZE := 15728640
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 18874368
#BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1258291200
#BOARD_CACHEIMAGE_PARTITION_SIZE := 157286400
#BOARD_USERDATAIMAGE_PARTITION_SIZE := 5073010688
BOARD_FLASH_BLOCK_SIZE := 131072

# Recovery
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_15x24.h\"
BOARD_SUPPRESS_EMMC_WIPE := true
BOARD_TOUCH_RECOVERY := true

# TWRP
# TW_CUSTOM_THEME := /home/yurius/omni/device/digma/plane_7565n/twres
HAVE_SELINUX := true
#TW_THEME := landscape_mdpi
TW_THEME := portrait_hdpi
#DEVICE_RESOLUTION := 600x1024
TW_IGNORE_MAJOR_AXIS_0 := true
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TW_NO_REBOOT_BOOTLOADER := false
BOARD_HAS_NO_REAL_SDCARD := true
RECOVERY_SDCARD_ON_DATA := true
TW_DEFAULT_EXTERNAL_STORAGE := true
TW_EXTERNAL_STORAGE_PATH := "/external_sd"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "external_sd"
# TW_ALLOW_PARTITION_SDCARD := true
TW_ROTATION := 270
#RECOVERY_TOUCHSCREEN_SWAP_XY := true 
#RECOVERY_TOUCHSCREEN_FLIP_Y := true 
#RECOVERY_TOUCHSCREEN_FLIP_X := true
#BOARD_HAS_FLIPPED_SCREEN := true
# USB Mounting
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/20200000.usb/gadget/lun%d/file

# Misc
# TW_NEVER_UNMOUNT_SYSTEM := true
TW_NO_SCREEN_TIMEOUT := true
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 190
TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true
ARCH_ARM_HAVE_NEON := true
# TW_EXTRA_LANGUAGES := true
#TW_DEFAULT_LANGUAGE := ru
TW_INCLUDE_CRYPTO := true
# TWRP_INCLUDE_LOGCAT := true
# TW_ALWAYS_RMRF := true
TW_EXCLUDE_SUPERSU := true

# Copying libminuitwrp.so
#PRODUCT_COPY_FILES += \
#    /home/yurius/omni/device/digma/plane_7565n/libminuitwrp.so:/home/yurius/omni/out/target/product/plane_7565n/recovery/root/sbin/libminuitwrp.so

